version: '3'
services:
  db:
    image: mysql:5.7
    environment:
        - MYSQL_ROOT_PASSWORD=itemapp
        - MYSQL_DATABASE=itemapp
        - MYSQL_USER=itemapp
        - MYSQL_PASSWORD=itemapp
    ports:
    - "3307:3306"
  web:
    build: .
    command: revel run app
    ports:
    - "9000:9000"
    volumes:
    - ./app:/go/src/app
